<?php include "head.phtml" ?>

<body class="m4-cloak">

<?php include "header.phtml" ?>

<div class="hero hero-bg">
    <div class="container">
        <div class="row">
            <div class="cell-md-6 cell-lg-7 order-2 order-md-1">
                <div class="text-center text-left-md">
                    <div class="display3 fg-dark"><span class="reduce-3 enlarge-1-md">Page not found <span class="fg-red">404</span></span>
                    </div>
                    <div class="text-leader fg-dark">
                        <span class="reduce-1 enlarge-1-md">
                            Sorry, requested page is not found. Please goto main page or search report!
                        </span>
                    </div>
                    <div class="mt-10 d-none d-block-md">
                        <a href="/" class="button secondary large"><span class="mif-arrow-left"></span> Goto main page</a>
                    </div>
                    <div class="mt-10 d-none-md">
                        <a href="/" class="button secondary"><span class="mif-arrow-left"></span> Goto main page</a>
                    </div>
                </div>
            </div>
            <div class="cell-md-6 cell-lg-5 order-1 order-md-2">
            </div>
        </div>
    </div>
</div>

<div class="container-fluid" style="background: #ced7dc">
    <div class="container pt-5 pb-5">
        <div class="row">
            <div class="cell-md-2"></div>
            <div class="cell-md-8">
                <form action="/scams" method="get">
                    <input type="text" class="input-large" name="q"
                           data-role="input"
                           data-prepend="<span class='text-leader'>Search:</span>"
                           data-cls-prepend=" d-none d-block-md"
                           data-search-button="true"
                           placeholder="Enter domain, resource or company name">
                </form>
            </div>
            <div class="cell-md-2"></div>
        </div>
    </div>
</div>


<div class="container-fluid services">
    <div class="container pt-5 pb-5 pt-10-md pb-10-md">
        <div class="text-center text-leader2 mt-10">
            <p class="reduce-1 enlarge-1-md pl-5-fs pr-5-fs pl-20-md pr-20-md">
                The <span class="text-bold">CryptoScam<span class="fg-red">Alert</span></span> database contains the most up-to-date information about Crypto ICOs, Crypto Blogers,
                Crypto Exchanges and how some of them scam people.
                If you've witnessed or been the victim of crypto scam, please report it <a href="add.html">here!</a>
            </p>
        </div>

        <div class="d-none1">
            <hr class="thin bg-gray mt-10 mb-4" style="width: 300px">
            <div class="text-center text-normal" style="background: url('images/logo-no-text-transparency.png') center center no-repeat; background-size: contain;">
                <h2>DONATION</h2>
                Feel free to make a donation to CryptoScamAlert.com to support our work.
                <br>We really appreciate your help!
                <br>
                <br><span class="text-normal">PayPal:</span> <span class="text-bold">cryptocheaters@gmail.com</span>
                <br><span class="text-normal">BTC:</span> <span class="text-bold">1M24NovHG8zcrpa3z28cpDGy4eBxicKure</span>
                <br><span class="text-normal">ETH:</span> <span class="text-bold">0xebE321bc7a19dDbdA2550068840fdE5e0FfeE542</span>
            </div>
            <hr class="thin bg-gray mt-4 mb-4" style="width: 300px">
        </div>
    </div>
</div>

<div class="container-fluid promotion fg-white">
    <div class="container pb-5 pt-5">
        <div class="text-upper text-bold">Getting started</div>
        <div class="fg-gray reduce-1">
            If you've witnessed or been the victim of crypto scam, please report it here.
            Registration on the website is very simple. You just need an email and password.
            No any personal information needed. <span class="text-bold fg-white">All reports are anonymous!</span>
            You can upload pictures of scammers along with any other details and proofs.
            Thank you for helping us making the crypto world Cleaner and Safe!
            Register today at <a href="#" class="fg-orange">here</a> and publish info about scammers.
        </div>
    </div>
</div>

<?php include "footer.phtml" ?>

<?php include "foot.phtml" ?>