<?php include "head.phtml" ?>

<?php include "header.phtml" ?>

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="cell-md-10 order-2 order-md-1">
                <h1>Report new scam</h1>
                <div class="text-leader2">
                    If you are a victim of crypto fraud or know about such facts, please share this information and help other people not to become a victim of scammers. Let's make the crypto world clean and safe together!
                </div>
            </div>
            <div class="cell-md-2 order-1 order-md-2 d-flex flex-align-center">
                <img src="<?php echo TEMPLATE_PATH?>images/logo-no-text.png">
            </div>
        </div>

        <hr class="mb-5 mt-5">

        <div class="mb-10">
            <form class="mb-10" data-role="validator" action="javascript:" onsubmit="addReport(this)" enctype="multipart/form-data">
                <div class="row mt-4">
                    <div class="cell-md-8 pr-0 pr-8-md">

                        <label class="text-leader">Scammer name:</label>
                        <input type="text" data-role="input" name="name" placeholder="Enter scammer name" data-validate="minlength=1">
                        <span class="invalid_feedback">Please enter a scammer name</span>
                        <div class="text-small">
                            Scammer's personal name or the company name.
                        </div>

                        <div class="mt-4">
                            <label class="text-leader">Scam description: <span class="text-small float-right mt-3 bg-cyan fg-white p-1">use markdown</span></label>
                            <textarea style="min-height: 400px" name="desc"></textarea>
                            <div class="text-small">Describe in detail how you became a victim of a fraudster.</div>
                        </div>

                    </div>

                    <div class="cell-md-4">
                        <label class="text-leader">Scam type:</label>
                        <select data-role="select" data-filter="false" name="type" data-cls-drop-list="d-menu simple-menu">
                            <?php if (isset($report_types) && count($report_types) > 0) foreach ($report_types as $key => $val) {?>
                                <option value="<?php echo $key ?>"><?php echo $val ?></option>
                            <?php }?>
                        </select>

                        <br>
                        <div class="mt-4">
                            <label class="text-leader">Search Tags:</label>
                            <input type="text" data-role="tag-input" data-max-tags="5" name="tags" data-tag-trigger="Comma, Enter">
                            <div class="text-small mt-1">Enter tags for this scam. Maximum 5 tags. Use <kbd>,</kbd> or <kbd>Enter</kbd> to add tag.</div>
                        </div>

                        <div class="mt-4">
                            <label class="text-leader">Scammer's link:</label>
                            <input type="text" data-role="input" name="link" placeholder="Enter link to the scammer's resource. Ex: https://site.com">
                            <div class="text-small mt-1">Link to the scammer's social media profile, blog or the website</div>
                        </div>

                        <br>
                        <label class="text-leader">
                            Photo evidence:
                        </label>
                        <div class="text-small mb-2">
                            You can add more than one image Subscribing ICO or scammers working as a team.
                        </div>

                        <input type="file" data-role="file" data-button-title="Select file or drop it here" data-mode="button" data-cls-component="drop-zone" multiple>
                    </div>
                </div>

                <hr class="mt-4 mb-4">

                <div class="d-none" id="evidence-template">
                    <span class="button square alert z-1"><span class="mif-bin"></span></span>
                    <div class="photo-container"><img/></div>
                    <input type="hidden"/>
                    <textarea placeholder="Enter evidence short description..."></textarea>
                </div>

                <div id="evidences">

                </div>

                <hr class="mt-4 mb-8">

                <div class="form-actions">
                    <button class="button alert">Report scam</button>
                    <a href="index.html" class="button link no-decor"><span class="fg-hero fg-dark-hover">Cancel</span></a>
                </div>

            </form>
        </div>
    </div>
</div>

<footer>
    <?php include "footer.phtml" ?>
</footer>

<?php include "foot.phtml" ?>