<div class="container pt-10 pb-10">
    <div class="row">
        <div class="cell-lg-7 pr-10-lg">
            <div class="text-upper text-bold">Why Crypto<span class="fg-red">Cheaters</span></div>
            <div class="text-small fg-gray">
                We are creating the  list of scam Initial Coin Offering (ICO)s and other crypto services such as scam crypto exchanges and social media crypto scammers. All information, proofs, investigations  came from different people  that witnessed or are victims of crypto scams and who cares the crypto community from scammers and fraudulent ICOs. Users post as much information as they can including the descriptions of the incidents, pictures of scammers and other  proofs of the scams.
                All credits belong to our users who submit their reports. All data  put together by CryptoCheaters website to help with information and provide knowledge for ICO investors and crypto enthusiast and to raise awareness about all kind of crypto scams.
                We really hope this information in the nearest future will be noted by authorities such as SEC and Interpol and may help them to bring the criminals to justice.
            </div>
        </div>

        <div class="cell-lg-5">
            <div class="text-upper text-bold">Donation</div>
            <div class="text-small fg-gray">
                <div class="mb-1">
                    Feel free to make a donation to <span class="text-bold text-upper fg-white">Crypto<span class="fg-red">Cheaters</span></span> to support our work.
                    <br>We really appreciate your help!
                </div>

                <span>PayPal:</span> <span class="fg-white">cryptocheaters@gmail.com</span>
                <br><span>BTC:</span> <span class="fg-white">1M24NovHG8zcrpa3z28cpDGy4eBxicKure</span>
                <br><span>ETH:</span> <span class="fg-white">0xebE321bc7a19dDbdA2550068840fdE5e0FfeE542</span>
            </div>

            <br>
            <div class="text-upper text-bold">Support</div>
            <div class="text-small fg-gray"><a href="mailto:support@cryptocheaters.com" class="fg-orange">support@cryptocheaters.com</a></div>
        </div>
    </div>

    <hr class="thin mt-4" style="background: #333">

    <div class="d-flex mt-4" style="color: #707070">
        <?php include "copyright.phtml" ?>
        <button class="button square ml-auto bg-transparent fg-white" type="button" id="go-to-top"><span class="mif-chevron-thin-up"></span></button>
    </div>
</div>
