<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="<?php echo TEMPLATE_PATH?>metro/css/metro-all.css">
    <link rel="stylesheet" href="<?php echo TEMPLATE_PATH?>css/site.css">
    <title><?php echo isset($page_title) ? $page_title : "CryptoCheaters - The whole truth about crypto scammers" ?></title>
</head>
