<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <meta name="description" content="<?php echo isset($meta) && isset($meta["description"]) ? $meta["description"] : 'If you`ve witnessed or been the victim of crypto scam or fraud, please report it to CryptoScamAlert.com. Report fraud and other suspicious activity involving cryptocurrency.' ?>"/>
    <meta name="keywords" content="<?php echo isset($meta) && isset($meta["keywords"]) ? $meta["keywords"] : ""?> report crypto scam, report crypto fraud,crypto scam, crypto cheaters, crypto scammers, crypto ico scam, crypto blogger scam" />
    <meta name="author" content=" CryptoScamAlert.com ">
    <meta name="robots" content="index,follow" />
    <meta name="googlebot" content="index,follow" />

    <meta name="metro4:cloak_duration" content="100" />

    <?php if (isset($styles)) foreach ($styles as $style) { ?>
        <link rel="stylesheet" href="/<?php echo TEMPLATE_PATH . $style . (PRODUCTION_MODE ? "" : "?rnd=". rand())?>">
    <?php } ?>

    <title><?php echo isset($page_title) ? $page_title : "CryptoScamAlert.com - The whole truth about crypto scammers" ?></title>
</head>
<body class="m4-cloak <?php echo isset($body_class) ? $body_class : "" ?>">
