<?php include "head.phtml" ?>

<?php include "header.phtml" ?>

<div class="hero hero-bg">
    <div class="container">
        <div class="row">
            <div class="cell-md-6 cell-lg-7 order-2 order-md-1">
                <div class="text-center text-left-md">
                    <div class="display3 fg-dark"><span class="reduce-3 enlarge-1-md">Crypto<span class="fg-red">Cheaters</span></span>
                    </div>
                    <div class="text-leader fg-dark"><span class="reduce-1 enlarge-1-md">
                    Regularly updated database of crypto frauds reported by real victims.
                    Read, Report and Help us making the Crypto World Healthier, Cleaner and Safe!
                    <br><br><span class="text-bold">ARE YOU A VICTIM?  REPORT IT!</span>
                </span></div>
                    <div class="mt-10 d-none d-block-md">
                        <a href="#" class="button secondary large">View scams</a>
                        <a href="<?php echo $_SESSION['current'] ? "/add" : "/login" ?>" class="button alert large">Report new scam</a>
                    </div>
                    <div class="mt-10 d-none-md">
                        <a href="#" class="button secondary">View scams</a>
                        <a href="<?php echo $_SESSION['current'] ? "/add" : "/login" ?>" class="button alert">Report new scam</a>
                    </div>
                </div>
            </div>
            <div class="cell-md-6 cell-lg-5 order-1 order-md-2">
            </div>
        </div>
    </div>
</div>

<div class="container-fluid" style="background: #ced7dc">
    <div class="container pt-5 pb-5">
        <div class="row">
            <div class="cell-md-2"></div>
            <div class="cell-md-8">
                <div class="d-none d-block-md">
                    <input type="text" class="input-large"
                           data-role="input"
                           data-prepend="<span class='text-leader'>CryptoCheaters:</span>"
                           data-search-button="true"
                           placeholder="Enter domain, resource or company name">
                </div>
                <div class="d-none-md">
                    <input type="text"
                           data-role="input"
                           data-search-button="true"
                           placeholder="Enter domain, resource or company name">
                </div>
            </div>
            <div class="cell-md-2"></div>
        </div>
    </div>
</div>


<div class="container-fluid services">
    <div class="container pt-5 pb-5 pt-10-md pb-10-md">
        <div class="row">
            <div class="cell-lg-4">
                <div class="service-item m-4">
                    <span class="mif-eye mif-6x fg-hero"></span>
                    <div class="h4 fg-hero2">We follow</div>
                    <div>
                        We are constantly monitoring the crypto currency market in search of fraudsters and how do they
                        work.
                        If you are a Victim of any Crypto Scam - Please report the incident to <a href="/">CryptoCheaters.com</a>
                    </div>
                </div>
            </div>
            <div class="cell-lg-4">
                <div class="service-item m-4">
                    <span class="mif-thumbs-up mif-6x fg-hero"></span>
                    <div class="h4 fg-hero2">Actual database</div>
                    <div>
                        Our database is constantly updated by us and users of Crypto Cheaters.
                        If you've witnessed or been the victim of crypto scam, please report it here.
                        It may help us to bring the offender to justice and make sure this doesn't happen to anyone
                        else.
                    </div>
                </div>
            </div>
            <div class="cell-lg-4">
                <div class="service-item m-4">
                    <span class="mif-users mif-6x fg-hero"></span>
                    <div class="h4 fg-hero2">Free and Anonymous!</div>
                    <div>
                        This is a free and user-friendly project. We keep your privacy.
                        You just need to have an email to register.
                        No other personal details required. All reports are Anonymous!
                    </div>
                </div>
            </div>
        </div>

        <div class="text-center text-leader2 mt-10">
            <p class="reduce-1 enlarge-1-md pl-5-fs pr-5-fs pl-20-md pr-20-md">
                The <span class="text-bold">Crypto<span class="fg-red">Cheaters</span></span> database contains the most up-to-date information about Crypto ICOs, Crypto Blogers,
                Crypto Exchanges and how some of them scam people.
                If you've witnessed or been the victim of crypto scam, please report it <a href="/add">here!</a>
            </p>
        </div>

        <div class="d-none1">
            <hr class="thin bg-gray mt-10 mb-4" style="width: 300px">
            <div class="text-center text-normal" style="background: url('images/logo-no-text-transparency.png') center center no-repeat; background-size: contain;">
                <h2>DONATION</h2>
                Feel free to make a donation to Cryptocheaters.com to support our work.
                <br>We really appreciate your help!
                <br>
                <br><span class="text-normal">PayPal:</span> <span class="text-bold">cryptocheaters@gmail.com</span>
                <br><span class="text-normal">BTC:</span> <span class="text-bold">1M24NovHG8zcrpa3z28cpDGy4eBxicKure</span>
                <br><span class="text-normal">ETH:</span> <span class="text-bold">0xebE321bc7a19dDbdA2550068840fdE5e0FfeE542</span>
            </div>
            <hr class="thin bg-gray mt-4 mb-4" style="width: 300px">
        </div>
    </div>
</div>

<div class="container-fluid promotion fg-white">
    <div class="container pb-5 pt-5">
        <div class="text-upper text-bold">Getting started</div>
        <div class="fg-gray reduce-1">
            If you've witnessed or been the victim of crypto scam, please report it here.
            Registration on the website is very simple. You just need an email and password.
            No any personal information needed. <span class="text-bold fg-white">All reports are anonymous!</span>
            You can upload pictures of scammers along with any other details and proofs.
            Thank you for helping us making the crypto world Cleaner and Safe!
            Register today at <a href="#" class="fg-orange">here</a> and publish info about scammers.
        </div>
    </div>
</div>

<div class="container-fluid bg-light">
    <div class="container pt-10 pb-10">
        <div class="display1 fg-hero2 mb-0">Top on <span class="fg-dark">Crypto</span><span class="fg-red">Cheaters</span></div>
        <div class="text-leader2">
            Below are the top scammers in the CryptoCheaters database
        </div>

        <hr class="bg-gray thin mt-2">

        <div class="row">
            <div class="cell-lg-4">
                <div class="feature">
                    <div class="h5 fg-hero2 mb-1">Microsoft</div>
                    <div class="mb-2">Scam type: <span class="text-bold">ICO</span></div>
                    <div>
                        Suns are the captains of the virtual collision course. Quinoa combines greatly with
                        crushed pumpkin seeds. Onus de magnum cursus, imperium saga!
                    </div>
                    <div>
                        <hr class="bg-lightGray thin mt-2">
                        <a href="#">See more...</a>
                    </div>
                </div>
            </div>
            <div class="cell-lg-4">
                <div class="feature">
                    <div class="h5 fg-hero2 mb-1">Apple</div>
                    <div class="mb-2">Scam type: <span class="text-bold">Telegram</span></div>
                    <div>
                        Suns are the captains of the virtual collision course. Quinoa combines greatly with
                        crushed pumpkin seeds. Onus de magnum cursus, imperium saga!
                    </div>
                    <div>
                        <hr class="bg-lightGray thin mt-2">
                        <a href="#">See more...</a>
                    </div>
                </div>
            </div>
            <div class="cell-lg-4">
                <div class="feature">
                    <div class="h5 fg-hero2 mb-1">Mirohost</div>
                    <div class="mb-2">Scam type: <span class="text-bold">Other</span></div>
                    <div>
                        Suns are the captains of the virtual collision course. Quinoa combines greatly with
                        crushed pumpkin seeds. Onus de magnum cursus, imperium saga!
                    </div>
                    <div>
                        <hr class="bg-lightGray thin mt-2">
                        <a href="#">See more...</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="cell-lg-4">
                <div class="feature">
                    <div class="h5 fg-hero2 mb-1">Bitcoin.com</div>
                    <div class="mb-2">Scam type: <span class="text-bold">Crypto Blog</span></div>
                    <div>
                        Everyone just loves the keenness of chicken paste decorated with mustard. Tribbles walk
                        with coordinates at the virtual cosmos!
                    </div>
                    <div>
                        <hr class="bg-lightGray thin mt-2">
                        <a href="#">See more...</a>
                    </div>
                </div>
            </div>
            <div class="cell-lg-4">
                <div class="feature">
                    <div class="h5 fg-hero2 mb-1">Facebook</div>
                    <div class="mb-2">Scam type: <span class="text-bold">Crypto Exchange</span></div>
                    <div>
                        Suns are the captains of the virtual collision course. Quinoa combines greatly with
                        crushed pumpkin seeds. Onus de magnum cursus, imperium saga!
                    </div>
                    <div>
                        <hr class="bg-lightGray thin mt-2">
                        <a href="#">See more...</a>
                    </div>
                </div>
            </div>
            <div class="cell-lg-4">
                <div class="feature">
                    <div class="h5 fg-hero2 mb-1">Google</div>
                    <div class="mb-2">Scam type: <span class="text-bold">ICO</span></div>
                    <div>
                        Suns are the captains of the virtual collision course. Quinoa combines greatly with
                        crushed pumpkin seeds. Onus de magnum cursus, imperium saga!
                    </div>
                    <div>
                        <hr class="bg-lightGray thin mt-2">
                        <a href="#">See more...</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="mt-10">
            <hr class="bg-gray thin mb-10">
            <a href="#" class="text-leader no-decor fg-hero2 fg-dark-hover">See all scammers <span
                    class="mif-arrow-right"></span></a>
        </div>

    </div>
</div>

<div class="container-fluid promotion">
    <div class="container">
        <div class="bg-transparent" data-role="carousel" data-auto-start="true" data-width="100%" data-height="50"
             data-bullets="false" data-controls="false" data-direction="right" data-duration="1500" data-period="10000">
            <div class="slide">
                <a href="https://metroui.org.ua" class="promotion-link"><span class="reduce-2 enlarge-md">Metro 4 is a Best in the World library for WebDev! <span
                            class="mif-chevron-right mif-3x"></span></span></a>
            </div>
            <div class="slide">
                <a href="https://builder.metroui.org.ua" class="promotion-link"><span class="reduce-2 enlarge-md">Create custom components set with simple Metro 4 Builder! <span
                            class="mif-chevron-right mif-3x"></span></span></a>
            </div>
        </div>
    </div>
</div>

<footer>
    <?php include "footer.phtml" ?>
</footer>

<?php include "foot.phtml" ?>

