<?php include "head.phtml" ?>

<?php include "header.phtml" ?>

<div class="hero hero-bg">
    <div class="container">
        <div class="row">
            <div class="cell-md-6 cell-lg-7 order-2 order-md-1">
                <div class="text-center text-left-md">
                    <div class="display3 fg-dark"><span class="reduce-3 enlarge-1-md">Crypto<span class="fg-red">ScamAlert</span></span>
                    </div>
                    <div class="text-leader fg-dark"><span class="reduce-1 enlarge-1-md">
                    Regularly updated database of crypto frauds reported by real victims.
                    Read, Report and Help us making the Crypto World Healthier, Cleaner and Safe!
                    <br><br><span class="text-bold">ARE YOU A VICTIM?  REPORT IT!</span>
                </span></div>
                    <div class="mt-10 d-none d-block-md">
                        <a href="/crypto_scammers" class="button secondary large">View scams</a>
                        <a href="<?php echo $_SESSION['current'] ? "/report_crypto_scam" : "/login" ?>" class="button alert large">Report new scam</a>
                        <a href="/verification" class="button warning large">Request verification</a>
                    </div>
                    <div class="mt-10 d-none-md">
                        <a href="/crypto_scammers" class="button secondary">View scams</a>
                        <a href="<?php echo $_SESSION['current'] ? "/report_crypto_scam" : "/login" ?>" class="button alert">Report new scam</a>
                        <a href="/verification" class="button warning">Request verification</a>
                    </div>
                </div>
            </div>
            <div class="cell-md-6 cell-lg-5 order-1 order-md-2">
            </div>
        </div>
    </div>
</div>

<div class="container-fluid" style="background: #ced7dc">
    <div class="container pt-5 pb-5">
        <div class="row">
            <div class="cell-md-2"></div>
            <div class="cell-md-8">
                <form action="/crypto_scammers" method="get">
                    <input type="text" class="input-large" name="q"
                           data-role="input"
                           data-prepend="<span class='text-leader'>Search:</span>"
                           data-cls-prepend=" d-none d-block-md"
                           data-search-button="true"
                           placeholder="Enter domain, resource or company name">
                </form>
            </div>
            <div class="cell-md-2"></div>
        </div>
    </div>
</div>


<div class="container-fluid services">
    <div class="container pt-5 pb-5 pt-10-md pb-10-md">
        <div class="row">
            <div class="cell-lg-4">
                <div class="service-item m-4">
                    <span class="mif-eye mif-6x fg-hero"></span>
                    <div class="h4 fg-hero2">We follow</div>
                    <div>
                        We are constantly monitoring the crypto currency market in search of fraudsters and how do they
                        work.
                        If you are a Victim of any Crypto Scam - Please report the incident to <a href="/">CryptoScamAlert.com</a>
                    </div>
                </div>
            </div>
            <div class="cell-lg-4">
                <div class="service-item m-4">
                    <span class="mif-thumbs-up mif-6x fg-hero"></span>
                    <div class="h4 fg-hero2">Actual database</div>
                    <div>
                        Our database is constantly updated by us and users of CryptoScamAlert.
                        If you've witnessed or been the victim of crypto scam, please report it here.
                        It may help us to bring the offender to justice and make sure this doesn't happen to anyone
                        else.
                    </div>
                </div>
            </div>
            <div class="cell-lg-4">
                <div class="service-item m-4">
                    <span class="mif-users mif-6x fg-hero"></span>
                    <div class="h4 fg-hero2">Free and Anonymous!</div>
                    <div>
                        This is a free and user-friendly project. We keep your privacy.
                        You just need to have an email to register.
                        No other personal details required. All reports are Anonymous!
                    </div>
                </div>
            </div>
        </div>

        <div class="text-center text-leader2 mt-10">
            <p class="reduce-1 enlarge-1-md pl-5-fs pr-5-fs pl-20-md pr-20-md">
                The <span class="text-bold">Crypto<span class="fg-red">ScamAlert</span></span> database contains the most up-to-date information about Crypto ICOs, Crypto Bloggers,
                Crypto Exchanges and how some of them scam people.
                If you've witnessed or been the victim of crypto scam, please report it <a href="/report_crypto_scam">here!</a>
            </p>
        </div>

        <div class="d-none">
            <hr class="thin bg-gray mt-10 mb-4" style="width: 300px">
            <div class="text-center text-normal" style="background: url('images/logo-no-text-transparency.png') center center no-repeat; background-size: contain;">
                <h2>DONATION</h2>
                Feel free to make a donation to CryptoScamAlert.com to support our work.
                <br>We really appreciate your help!
                <br>
                <br><span class="text-normal">PayPal:</span> <span class="text-bold">cryptocheaters@gmail.com</span>
                <br><span class="text-normal">BTC:</span> <span class="text-bold">1M24NovHG8zcrpa3z28cpDGy4eBxicKure</span>
                <br><span class="text-normal">ETH:</span> <span class="text-bold">0xebE321bc7a19dDbdA2550068840fdE5e0FfeE542</span>
            </div>
            <hr class="thin bg-gray mt-4 mb-4" style="width: 300px">
        </div>
    </div>
</div>

<div class="container-fluid promotion fg-white">
    <div class="container pb-5 pt-5">
        <div class="text-upper text-bold">Getting started</div>
        <div class="fg-gray reduce-1">
            If you've witnessed or been the victim of crypto scam, please report it here.
            Registration on the website is very simple. You just need an email and password.
            No any personal information needed. <span class="text-bold fg-white">All reports are anonymous!</span>
            You can upload pictures of scammers along with any other details and proofs.
            Thank you for helping us making the crypto world Cleaner and Safe!
            Register today at <a href="#" class="fg-orange">here</a> and publish info about scammers.
        </div>
    </div>
</div>

<?php if (isset($newest) && is_array($newest) && count($newest) > 0) {?>

<div class="container-fluid bg-light">
    <div class="container pt-10 pb-10">
        <div class="display1 fg-hero2 mb-0">Newest on <span class="fg-dark">Crypto</span><span class="fg-red">ScamAlert</span></div>
        <div class="text-leader2">
            Below are the latest added scammers to the CryptoScamAlert database
        </div>

        <hr class="bg-gray thin mt-2">

        <div class="row">

        <?php foreach ($newest as $index => $report) {?>
            <div class="cell-lg-4">
                <div class="scam-card bg-white border">
                    <?php include "scam-card.phtml" ?>
                </div>
            </div>
        <?php
        if ($index + 1 % 3 === 0) { ?>
        </div>
        <div class="row">
        <?php }}?>

        </div>

        <div class="mt-4">
            <a href="/crypto_scammers" class="text-leader no-decor fg-hero2 fg-dark-hover">
                See all reports <span class="mif-arrow-right"></span>
            </a>
        </div>

    </div>
</div>

<?php }?>

<?php if (isset($reports) && is_array($reports) && count($reports) > 0) {?>

<div class="container-fluid">
    <div class="container pt-10 pb-10">
        <div class="display1 fg-hero2 mb-0">Top on <span class="fg-dark">Crypto</span><span class="fg-red">ScamAlert</span></div>
        <div class="text-leader2">
            Below are the top scammers in the CryptoScamAlert database
        </div>

        <hr class="bg-gray thin mt-2">

        <div class="row">

        <?php foreach ($reports as $index => $report) {?>
            <div class="cell-lg-4">
                <div class="scam-card border">
                    <?php include "scam-card.phtml" ?>
                </div>
            </div>
        <?php
        if ($index + 1 % 3 === 0) { ?>
        </div>
        <div class="row">
        <?php }}?>

        </div>

        <div class="mt-4">
            <a href="/crypto_scammers" class="text-leader no-decor fg-hero2 fg-dark-hover">
                See all reports <span class="mif-arrow-right"></span>
            </a>
        </div>

    </div>
</div>

<?php }?>

<?php if (isset($evidences) && is_array($evidences) && count($evidences) > 0) {?>

<div class="container-fluid bg-light">
    <div class="container pt-10 pb-10">
        <div class="display1 fg-hero2 mb-0"><span class="fg-dark">Crypto</span><span class="fg-red">ScamAlert</span> Gallery</div>
        <div class="text-leader2">
            Random scammers in the CryptoScamAlert database
        </div>

        <hr class="bg-gray thin mt-2">

        <div id="evidences" class="row" style="background-image: none">
            <?php foreach ($evidences as $index => $evidence) {?>
                <div class="evidence present-photo">
                    <div class="photo-container c-pointer">
                        <a href="/crypto_scam_report/<?php echo $evidence['evidence_report']?>">
                            <img src="<?php echo $evidence['evidence_image']?>" data-evidence="<?php echo $evidence['evidence_id']?>" data-report="<?php echo $evidence['evidence_report']?>">
                        </a>
                    </div>
                </div>
            <?php }?>
        </div>

    </div>
</div>

<?php }?>

<div class="container-fluid promotion">
    <div class="container">
        <div class="bg-transparent" data-role="carousel" data-auto-start="true" data-width="100%" data-height="50"
             data-bullets="false" data-controls="false" data-direction="right" data-duration="1500" data-period="10000">
            <div class="slide">
                <a href="https://metroui.org.ua" class="promotion-link"><span class="reduce-2 enlarge-md">Metro 4 is a Best in the World library for WebDev! <span
                            class="mif-chevron-right mif-3x"></span></span></a>
            </div>
            <div class="slide">
                <a href="https://builder.metroui.org.ua" class="promotion-link"><span class="reduce-2 enlarge-md">Create custom components set with simple Metro 4 Builder! <span
                            class="mif-chevron-right mif-3x"></span></span></a>
            </div>
            <div class="slide">
                <a href="https://github.com/olton/colorjs" class="promotion-link"><span class="reduce-2 enlarge-md"><span class="text-bold fg-cyan">Color<span class="fg-red">JS</span></span> is a javascript class designed to work with color.! <span
                            class="mif-chevron-right mif-3x"></span></span></a>
            </div>
        </div>
    </div>
</div>

<?php include "footer.phtml" ?>

<?php include "foot.phtml" ?>

