<?php include "head.phtml"?>
<body class="m4-cloak pt-0 h-vh-100">
    <div class="row h-100">
        <div class="cell-md-6 bg-hero">
            <div class="h-100 d-flex flex-column flex-justify-center flex-align-center">
                <div style="max-width: 300px" class="text-center mt-4 mb-4 mb-0-md mt-0-md">
                    <img src="<?php echo TEMPLATE_PATH ?>images/logo.png">
                    <div class="text-leader2">The whole truth about crypto scammers.</div>
                </div>
            </div>
        </div>
        <div class="cell-md-6 bg-white d-flex flex-column flex-justify-center">
            <form class="p-4 p-20-md" data-role="validator">
                <div class="h1">Login</div>
                <br>
                <input type="text" name="user-email" class="input-large" data-role="input" data-prepend="<span class='mif-envelop text-leader'>" placeholder="Enter your email..." data-validate="email">
                <span class="invalid_feedback">You must enter a valid email address!</span>
                <br>
                <input type="password" name="user-password" class="input-large" data-role="input" data-prepend="<span class='mif-lock text-leader'>" placeholder="Enter your password..." data-validate="minlength=8">
                <span class="invalid_feedback">Your password must contains min 8 symbols!</span>
                <br>
                <div class="form-actions d-none d-block-md">
                    <button class="button large secondary">Login to CryptoCheaters</button>
                    <a href="/" class="button large link no-decor" type="button"><span class="fg-hero fg-dark-hover">Cancel</span></a>
                </div>
                <div class="form-actions d-none-md">
                    <button class="button secondary">Login to CryptoCheaters</button>
                    <a href="/" class="button link no-decor" type="button"><span class="fg-hero fg-dark-hover">Cancel</span></a>
                </div>

                <hr class="mt-4">
                    <div class="mt-4 mb-4">
                        No account on CryptoCheaters.com? <a href="/signup">Sign Up now!</a>
                    </div>
                <hr class="mt-4">

                <div class="d-flex mt-4" style="color: #707070">
                    <small>
                        Copyright 2019-2020 by CryptoCheaters.com
                        <br>Design and programming by <a href="https://pimenov.com.ua" class="fg-orange">Serhii Pimenov</a>.
                        <br class="d-none-md"> Site created with <a href="https://metroui.org.ua" class="fg-orange">Metro 4</a>.
                    </small>
                </div>

            </form>
        </div>
    </div>
</body>
<?php include "foot.phtml"?>
