<?php if (isset($evidences) && is_array($evidences) && count($evidences) > 0) {?>

    <div class="container-fluid bg-light">
        <div class="container pt-10 pb-10">
            <div class="display1 fg-hero2 mb-0"><span class="fg-dark">Crypto</span><span class="fg-red">ScamAlert</span> Gallery</div>
            <div class="text-leader2">
                Random scammers in the CryptoScamAlert database
            </div>

            <hr class="bg-gray thin mt-2">

            <div id="image-grid" class="half-size"
                 data-use-background="true"
                 data-on-draw-item="imageGridDrawItem"
                 data-cls-image-grid-item="border bd-white border-2" style="margin: 0 -10px">
            </div>
        </div>
    </div>

<?php }?>
