<?php include "head.phtml"?>

<?php include "header.phtml"?>

<div class="container-fluid">
    <div class="container">
        <?php if (isset($report)) {?>
        <div class="row">
            <div class="cell-md-10 order-2 order-md-1">
                <h1>Scam Report</h1>
                <div class="text-leader2">
                    This report describes the fraudster and his actions, how the fraudster acts.
                </div>
                <div class="mt-1 text-muted">
                    Reported by : <?php echo $report['nickname'] . ", " . $report['report_created']?>
                </div>
            </div>
            <div class="cell-md-2 order-1 order-md-2 d-flex flex-align-center">
                <img src="/<?php echo TEMPLATE_PATH?>images/logo-no-text.png">
            </div>
        </div>

        <hr class="mb-5">

        <div class="d-flex flex-wrap flex-align-center">
            <?php if ($_SESSION['current']) {?>
                <div class="d-flex flex-align-center mr-4">
                    <button class="button info"><span class="mif-thumbs-up"></span> Vote this report</button>
                </div>
            <?php }?>
            <span>Total votes: <span class="text-leader2"><?php echo $report['report_likes']?></span></span>
            <div class="ml-auto-md mt-2 mt-0-md">
                <button class="button">Print</button>
                <?php if (intval($_SESSION['user']['admin']) === 1) {?>
                <button class="button alert" onclick="delReport(<?php echo $report['report_id']?>)">Delete</button>
                <?php }?>
            </div>
        </div>

        <hr class="mb-5 mt-5">

        <div class="">
            <div class="d-flex flex-nowrap flex-align-center">
                Tags: <input data-role="tag-input" data-static="true" value="<?php echo $report['report_tags']?>">
            </div>
        </div>

        <hr class="mb-5 mt-5">

        <div class="row">
            <div class="cell-lg-8 pr-0 pr-4-lg">

                <div class="report-label">Scammer's name</div>
                <div class="report-desc">
                    <?php echo $report['report_name']?>
                </div>

                <div class="report-label">Scam description</div>
                <div class="report-desc markdown-source"><?php echo $report['report_desc'] ?></div>

            </div>

            <div class="cell-lg-4">
                <div class="report-label">Scammer type</div>
                <div class="report-desc"><?php echo $report['report_type_name']?></div>

                <div class="report-label">Scammer's link</div>
                <div class="report-desc"><?php echo $report['report_link']?></div>

                <?php if (isset($evidences) && is_array($evidences) && count($evidences) > 0) {?>
                    <div class="report-label">Scammer's Photo</div>
                    <div id="evidences" class="report-evidences row" style="background-image: none">
                        <?php foreach ($evidences as $index => $evidence) {?>
                            <div class="evidence m-0 cell-6 cell-md-4 cell-lg-6">
                                <div class="photo-container c-pointer">
                                    <img src="<?php echo $evidence['evidence_image']?>" data-evidence="<?php echo $evidence['evidence_id']?>" data-report="<?php echo $evidence['evidence_report']?>">
                                </div>
                                <?php if ($evidence['evidence_desc'] !== '') {?>
                                <div class="p-2 bg-light text-small evidence-desc">
                                    <?php echo $evidence['evidence_desc']?>
                                </div>
                                <?php }?>
                            </div>
                        <?php }?>
                    </div>
                <?php }?>

                <br>

            </div>
        </div>

        <br>

        <?php }?>

    </div>
</div>

<?php include "footer.phtml" ?>

<?php include "foot.phtml"?>