<div class="text-small text-bold">Scammer</div>
<a class="no-decor" href="/crypto_scam_report/<?php echo $report['report_id']?>">
    <div class="h5 mb-3 mt-0 text-ellipsis scammer-name"><?php echo $report['report_name']?></div>
</a>
<div class="text-small">Scam type: <span class="text-bold"><?php echo $report['report_type_name']?></span></div>
<div class="text-small">Voted: <span class="text-bold"><?php echo $report['votes']?></span></div>
<div class="text-small">
    Reported by: <span class="text-bold"><?php echo $report['nickname']?></span>,
    at <span class="text-bold"><?php echo date("Y-m-d", strtotime($report['report_created']))?></span>
</div>
<div>
    <hr class="bg-lightGray thin mt-2">
    <div class="d-flex">
        <a href="/crypto_scam_report/<?php echo $report['report_id']?>">See details <span class="mif-arrow-right"></span></a>
        <div class="ml-auto">
            <button class="button square secondary small d-none" onclick="printReport(<?php echo $report['report_id']?>)"><span class="mif-print"></span></button>
            <?php if ($_SESSION['current'] && (($_SESSION['current']) === $report['report_user_id'] || intval($_SESSION['user']['admin']) === 1)) {?>
                <a class="button square secondary small" href="/update_crypto_scam_report/<?php echo $report['report_id']?>"><span class="mif-pencil"></span></a>
            <?php }?>
            <?php if (isset($_SESSION['user']) && intval($_SESSION['user']['admin']) === 1) {?>
                <button class="button square alert small" onclick="delReport(<?php echo $report['report_id']?>, '/crypto_scammers')"><span class="mif-bin"></span></button>
            <?php }?>
        </div>
    </div>
</div>
