<?php include "head.phtml" ?>

<div class="row h-100">
    <div class="cell-md-6 bg-hero">
        <div class="h-100 d-flex flex-column flex-justify-center flex-align-center">
            <div style="max-width: 300px" class="text-center mt-4 mb-4 mb-0-md mt-0-md">
                <img src="<?php echo TEMPLATE_PATH ?>images/logo.png">
                <div class="text-leader2">The whole truth about crypto scammers.</div>
            </div>
        </div>
    </div>
    <div class="cell-md-6 bg-white d-flex flex-column flex-justify-center">
        <form class="p-4 p-20-md" data-role="validator" action="javascript:" onsubmit="signup(this)">
            <div class="h1">Sign Up</div>
            <br>
            <input type="text" name="nickname" class="input-large" data-role="input" data-prepend="<span class='mif-user text-leader'>" placeholder="Enter your nickname..." data-validate="minlength=1">
            <span class="invalid_feedback">You must enter a valid email address!</span>
            <br>
            <input type="text" name="email" class="input-large" data-role="input" data-prepend="<span class='mif-envelop text-leader'>" placeholder="Enter your email..." data-validate="email">
            <span class="invalid_feedback">You must enter a valid email address!</span>
            <br>
            <input type="password" name="password" class="input-large" data-role="input" data-prepend="<span class='mif-lock text-leader'>" placeholder="Enter your password..." data-validate="minlength=8">
            <span class="invalid_feedback">Your password must contains min 8 symbols!</span>
            <br>
            <input type="password" name="password_check" class="input-large" data-role="input" data-prepend="<span class='mif-key text-leader'>" placeholder="Please confirm your password..." data-validate="minlength=8 equals=password">
            <span class="invalid_feedback">Your passwords must be identical!</span>
            <br>
            <div class="form-actions d-none d-block-md">
                <button class="button large secondary">Create account</button>
                <a href="/" class="button large link no-decor" type="button"><span class="fg-hero fg-dark-hover">Cancel</span></a>
            </div>
            <div class="form-actions d-none-md">
                <button class="button secondary">Create account</button>
                <a href="/" class="button link no-decor" type="button"><span class="fg-hero fg-dark-hover">Cancel</span></a>
            </div>

            <hr class="mt-4">
            <div class="mt-4 mb-4">
                You nave an account on CryptoCheaters.com? <a href="/login">Login now!</a>
            </div>
            <hr class="mt-4">

            <div class="d-flex mt-4" style="color: #707070">
                <?php include "copyright.phtml" ?>
            </div>

        </form>
    </div>
</div>

<?php include "foot.phtml" ?>
