<?php include "head.phtml" ?>

<?php include "header.phtml" ?>

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="cell-md-10 order-2 order-md-1">
                <h1>Terms and Conditions</h1>
                <div class="text-leader2">
                    Below is the text of the agreement on the use and operation of cryptoscamalert.com
                </div>
            </div>
            <div class="cell-md-2 order-1 order-md-2 d-flex flex-align-center">
                <img src="<?php echo TEMPLATE_PATH?>images/logo-no-text.png">
            </div>
        </div>
        <hr class="mb-5 mt-5">

        <div class="mb-10">
            <span class="text-upper text-bold">Crypto<span class="fg-red">ScamAlert</span></span> administration reserves the right to make changes without a notification to users. The site administration has the right to make changes to the Rules at any time, which come into force immediately.
            <br>
            <br>
            All information is provided in its original form, without warranty of completeness or timeliness, and without any other expressed or implied warranties. Access to the Site, as well as the use of its Content, is at the sole discretion and risk of the User.
            <br>
            <br>
            The administration does not make any representations or warranties towards the site and its Content, including, without limitation, with respect to the timeliness, relevance, accuracy, completeness, reliability, availability or compliance for any particular purpose of the Site and the Content. Also, the Administration is not responsible for changing, editing or deleting any information added by user to the Site.
            <br>
            <br>
            The Site Administration does not bear any responsibility for the links, photos, images, files, materials, comments, reviews and any other information posted by the Site Users.
            It is not the responsibility of the Administration to control the legality or illegality of the submitted information (any, including, but not limited to information in the form of various links, texts or archives), to determine the ownership or legality of the transfer, reception or use of this information.
        </div>
    </div>
</div>

<?php include "footer.phtml" ?>

<?php include "foot.phtml" ?>