<?php include "head.phtml" ?>

<?php include "header.phtml"?>

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="cell-md-10 order-2 order-md-1">
                <h1>Top Crypto Scammers <small>(<?php echo $length ?>)</small></h1>
                <div class="text-leader2">
                    Below are the list of newest scammers in the CryptoScamAlert database.
                </div>
            </div>
            <div class="cell-md-2 order-1 order-md-2 d-flex flex-align-center">
                <img src="<?php echo TEMPLATE_PATH?>images/logo-no-text.png">
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="container pt-5">
        <form action="/crypto_scammers" method="get">
            <input type="text" class="input-large" name="q"
                   data-role="input"
                   data-prepend="<span class='text-leader'>Search:</span>"
                   data-cls-prepend=" d-none d-block-md"
                   data-search-button="true"
                   placeholder="Enter domain, resource or company name" value="<?php echo isset($query) ? $query : ""?>">
        </form>
    </div>
</div>

<div class="container-fluid">
    <div class="container pb-10">
        <?php if (isset($reports) && count($reports) > 0) {?>

        <div class="mt-4 mb-4">
            <div id="pagination-top" data-view="top_crypto_scammers"
                 data-length="<?php echo isset($length) ? $length : 0?>"
                 data-rows="<?php echo isset($rows) ? $rows : 0?>"
                 data-page="<?php echo isset($page) ? $page : 0?>"
            ></div>
        </div>

        <div class="row">
            <?php foreach ($reports as $index => $report) {?>
            <div class="cell-lg-4">
                <div class="scam-card border">
                    <?php include "scam-card.phtml" ?>
                </div>
            </div>
            <?php
            if ($index + 1 % 3 === 0) { ?>
        </div>
        <div class="row">
            <?php }}?>
        </div>

        <div class="mt-4">
            <div id="pagination" data-view="top_crypto_scammers"
                 data-length="<?php echo isset($length) ? $length : 0?>"
                 data-rows="<?php echo isset($rows) ? $rows : 0?>"
                 data-page="<?php echo isset($page) ? $page : 0?>"
            ></div>
        </div>

        <?php } else {?>
        <div class="text-center text-leader2 mt-8">
            Sorry, we are nothing to show!
        </div>
        <?php } ?>


    </div>
</div>

<?php include "footer.phtml" ?>

<?php include "foot.phtml" ?>