<?php include "head.phtml" ?>

<?php include "header.phtml" ?>

<div class="container-fluid">
    <div class="container">
    <?php if (isset($report)) {?>
        <div class="row">
            <div class="cell-md-10 order-2 order-md-1">
                <h1>Scam Report</h1>
                <div class="mt-1 text-muted">
                    Reported by : <?php echo $report['nickname'] . ", " . date("d/m/Y", strtotime($report['report_created']))?>
                </div>
            </div>
            <div class="cell-md-2 order-1 order-md-2 d-flex flex-align-center">
                <img src="/<?php echo TEMPLATE_PATH?>images/logo-no-text.png">
            </div>
        </div>

        <hr class="mb-5">

        <div class="mb-10">
            <form class="mb-10" data-role="validator" action="javascript:" onsubmit="updateReport(this)" enctype="multipart/form-data">
                <input type="hidden" name="report_id" value="<?php echo $report['report_id'] ?>">
                <input type="hidden" name="report_owner" value="<?php echo $report['report_user_id'] ?>">
                <div class="row mt-4">
                    <div class="cell-md-8 pr-0 pr-8-md">

                        <label class="text-leader">Scammer's name:</label>
                        <input type="text" data-role="input" name="name" placeholder="Enter scammer name" data-validate="minlength=1" value="<?php echo $report['report_name']?>">
                        <span class="invalid_feedback">Please enter a scammer name</span>
                        <div class="text-small">
                            Scammer's personal name or the company name.
                        </div>

                        <div class="mt-4">
                            <label class="text-leader">Scam description: <a href="https://markdown-it.github.io/" target="_blank"><span class="text-small float-right mt-3 bg-cyan fg-white p-1">use markdown</span></a></label>
                            <textarea style="min-height: 400px" name="desc"><?php echo $report['report_desc']?></textarea>
                            <div class="text-small">Describe in detail how you became a victim of a fraudster.</div>
                        </div>

                    </div>

                    <div class="cell-md-4">
                        <label class="text-leader">Scam type:</label>
                        <select data-role="select" data-filter="false" name="type" data-cls-drop-list="d-menu simple-menu">
                            <?php if (isset($report_types) && is_array($report_types)) foreach ($report_types as $key => $val) {?>
                                <option value="<?php echo $key ?>" <?php echo intval($key) === intval($report['report_type']) ? "selected" : ""?> ><?php echo $val ?></option>
                            <?php }?>
                        </select>

                        <br>
                        <div class="mt-4">
                            <label class="text-leader">Search tags:</label>
                            <input type="text" data-role="tag-input" data-max-tags="5" name="tags" data-tag-trigger="Comma, Enter" value="<?php echo $report['report_tags']?>">
                            <div class="text-small mt-1">Enter tags for this scam. Maximum 5 tags. Use <kbd>,</kbd> or <kbd>Enter</kbd> to add tag.</div>
                        </div>

                        <div class="mt-4">
                            <label class="text-leader">Scammer's link:</label>
                            <input type="text" data-role="input" name="link" placeholder="Enter link to the scammer's resource. Ex: https://site.com" value="<?php echo $report['report_link']?>">
                            <div class="text-small mt-1">Link to the scammer's social media profile, blog or the website</div>
                        </div>

                        <br>
                        <label class="text-leader">
                            Scammer's photo:
                        </label>
                        <div class="text-small mb-2">
                            You can add more than one image Subscribing ICO or scammers working as a team.
                        </div>

                        <input type="file" data-role="file" data-button-title="Select file(s) or drop file(s) here" data-mode="button" data-cls-component="drop-zone" multiple>
                    </div>
                </div>

                <hr class="mt-4 mb-4">

                <div class="d-none" id="evidence-template">
                    <span class="button square alert z-1"><span class="mif-bin"></span></span>
                    <div class="photo-container"><img/></div>
                    <input type="hidden"/>
                    <textarea placeholder="Enter photo short description..."></textarea>
                </div>

                <?php if (isset($evidences) && is_array($evidences)) {?>
                <div id="evidences" class="report-evidences row">
                    <?php foreach ($evidences as $index => $evidence) {?>
                        <div class="evidence">
                            <span class="button square alert z-1"><span class="mif-bin"></span></span>
                            <div class="photo-container">
                                <img src="<?php echo $evidence['evidence_image']?>" data-evidence="<?php echo $evidence['evidence_id']?>" data-report="<?php echo $evidence['evidence_report']?>">
                            </div>
                            <input type="hidden" name="evidence[]" value="<?php echo $evidence['evidence_image']?>"/>
                            <textarea placeholder="Enter photo short description..." name="evidence_desc[]"><?php echo $evidence['evidence_desc']?></textarea>
                        </div>
                    <?php }?>
                </div>
                <?php }?>

                <hr class="mt-4 mb-8">

                <div class="form-actions">
                    <button class="button secondary">Update Report</button>
                    <button class="button link no-decor" type="button" onclick="back()"><span class="fg-hero fg-dark-hover">Cancel</span></button>
                </div>

            </form>
        </div>
    <?php }?>
    </div>
</div>

<?php include "footer.phtml" ?>

<?php include "foot.phtml" ?>